on:
  push:
    branches:
      - master

jobs:
  generate-llms:
    runs-on: ubuntu-latest
    steps:
      - name: Generate llms.txt with for profound site automatically on push
        uses: ignatius525/llms-text-gen/.github/actions/llms-gen@master
        with:
          root-url: https://www.tryprofound.com
          output-dir: ./tryprofound
          max-pages: 1000
          concurrency: 16
          use-playwright: false
